### ISSUE TITLE
Combining content for Story Map Cascade to Story Map Series

### ISSUE THREAD

**Issue by CRGore** [Esri/storymap-series#47]
I am customizing a web app using the Story Map Series (with tabs). However I would love to include the opening slider page from the Story Map Cascade application. 

Basically, I'd like for my web app to open with the initial Story Map Cascade slider and when the down-arrow is clicked I want to continue with the Story Map Series.

Is there a way to customize to code and make it happen or is it not even possible? :-)

Thanks in advance for the assistance.

**Comment by CRGore** [comment]
PLEASE HELP!

**Comment by iwittenmyer** [comment]
One approach would be to complete authoring the story map series, then create a separate story map cascade, and then embed the story map series in the cascade after the opening slider page.

**Comment by CRGore** [comment]
Thanks so much for your assistance Ian. I've been trying to figure this out for days! 🙂 

How would I embed the code for the sorry map series without messing up the Cascade?

Thanks again for the help.

**Comment by iwittenmyer** [comment]
this blog should cover the workflow
https://www.esri.com/arcgis-blog/products/story-maps/mapping/embedding-a-story-map-within-a-story-map/

**Comment by iwittenmyer** [comment]
i think the simplest way would be to create the cascade and then after the cover page section, add media, then switch to the link to content tab, and paste in the url to your map series.  if you want to minimize the header, you can also append &embed to the url.  then click the pencil in the lower left of the embedded map series, change the size to large, and then save
![image](https://user-images.githubusercontent.com/6155742/55435925-c8229e00-554f-11e9-9a2f-c9822627e5a1.png)

**Comment by CRGore** [comment]
IT WORKED! 🤗

Thanks so much for the help Ian. I truly appreciate you!
