### ISSUE TITLE
Issue with Content Security Policy - accessing main-config.js

### ISSUE THREAD

**Issue by ePantazisIBI** [Esri/storymap-series#52]
Hello I am trying to host an ARCGIS Story map on our server 
To run the test I am using an accessible map with ID: f2e9b762544945f390ca4ac3671cfa72
I am getting the following error with regards to the Content Security Policy. I below attach a screenshot.
I was geeting more errors but I added in my index.html where I  have the app the following tag  and getting just the one below 
	<meta http-equiv="Content-Security-Policy" content="script-src 'unsafe-inline' ">

![image](https://user-images.githubusercontent.com/56407590/126562199-f1633ccd-6441-4c1c-88b7-d1ea76abc3f3.png)

**Comment by oevans** [comment]
@ePantazisIBI -- Please contact [Esri Technical Support](https://support.esri.com) for help configuring this template on your own server.

Closing since this is not a BUG or ENH.
